export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      conversations: {
        Row: {
          id: string;
          clerk_user_id: string;
          channel: string;
          title: string;
          messages: Json;
          model: string | null;
          provider_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clerk_user_id: string;
          channel: string;
          title?: string;
          messages?: Json;
          model?: string | null;
          provider_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clerk_user_id?: string;
          channel?: string;
          title?: string;
          messages?: Json;
          model?: string | null;
          provider_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      categories: {
        Row: {
          slug: string;
          title: string;
          strapline: string;
          description: string;
          hero: string;
          accent: string;
          status: string;
          keywords: string[];
          sources: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          slug: string;
          title: string;
          strapline?: string;
          description?: string;
          hero?: string;
          accent?: string;
          status?: string;
          keywords?: string[];
          sources?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          slug?: string;
          title?: string;
          strapline?: string;
          description?: string;
          hero?: string;
          accent?: string;
          status?: string;
          keywords?: string[];
          sources?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      skills: {
        Row: {
          id: string;
          slug: string;
          title: string;
          description: string;
          category: string;
          body: string;
          accent: string;
          featured: boolean;
          visibility: string;
          origin: string;
          path: string | null;
          relative_dir: string | null;
          tags: string[];
          headings: Json;
          owner_name: string | null;
          sources: Json;
          automation: Json | null;
          updates: Json;
          agent_docs: Json;
          references_data: Json;
          agents_data: Json;
          source_url: string | null;
          canonical_url: string | null;
          sync_enabled: boolean;
          last_synced_at: string | null;
          version: number;
          created_at: string;
          updated_at: string;
          search_vector: unknown;
          icon_url: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          description?: string;
          category: string;
          body?: string;
          accent?: string;
          featured?: boolean;
          visibility?: string;
          origin: string;
          path?: string | null;
          relative_dir?: string | null;
          tags?: string[];
          headings?: Json;
          owner_name?: string | null;
          sources?: Json;
          automation?: Json | null;
          updates?: Json;
          agent_docs?: Json;
          references_data?: Json;
          agents_data?: Json;
          source_url?: string | null;
          canonical_url?: string | null;
          sync_enabled?: boolean;
          last_synced_at?: string | null;
          version?: number;
          created_at?: string;
          updated_at?: string;
          icon_url?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          description?: string;
          category?: string;
          body?: string;
          accent?: string;
          featured?: boolean;
          visibility?: string;
          origin?: string;
          path?: string | null;
          relative_dir?: string | null;
          tags?: string[];
          headings?: Json;
          owner_name?: string | null;
          sources?: Json;
          automation?: Json | null;
          updates?: Json;
          agent_docs?: Json;
          references_data?: Json;
          agents_data?: Json;
          source_url?: string | null;
          canonical_url?: string | null;
          sync_enabled?: boolean;
          last_synced_at?: string | null;
          version?: number;
          created_at?: string;
          updated_at?: string;
          icon_url?: string | null;
        };
        Relationships: [];
      };
      skill_versions: {
        Row: {
          id: string;
          skill_id: string;
          version: number;
          title: string;
          description: string;
          category: string;
          body: string;
          tags: string[];
          owner_name: string | null;
          visibility: string;
          sources: Json;
          automation: Json | null;
          updates: Json;
          agent_docs: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          skill_id: string;
          version: number;
          title: string;
          description?: string;
          category: string;
          body?: string;
          tags?: string[];
          owner_name?: string | null;
          visibility?: string;
          sources?: Json;
          automation?: Json | null;
          updates?: Json;
          agent_docs?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          skill_id?: string;
          version?: number;
          title?: string;
          description?: string;
          category?: string;
          body?: string;
          tags?: string[];
          owner_name?: string | null;
          visibility?: string;
          sources?: Json;
          automation?: Json | null;
          updates?: Json;
          agent_docs?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      imported_mcps: {
        Row: {
          id: string;
          name: string;
          description: string;
          manifest_url: string;
          homepage_url: string | null;
          transport: string;
          url: string | null;
          command: string | null;
          args: string[];
          env_keys: string[];
          headers: Json | null;
          tags: string[];
          raw: string;
          version: number;
          version_label: string;
          created_at: string;
          updated_at: string;
          icon_url: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string;
          manifest_url: string;
          homepage_url?: string | null;
          transport?: string;
          url?: string | null;
          command?: string | null;
          args?: string[];
          env_keys?: string[];
          headers?: Json | null;
          tags?: string[];
          raw?: string;
          version?: number;
          version_label?: string;
          created_at?: string;
          updated_at?: string;
          icon_url?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          manifest_url?: string;
          homepage_url?: string | null;
          transport?: string;
          url?: string | null;
          command?: string | null;
          args?: string[];
          env_keys?: string[];
          headers?: Json | null;
          tags?: string[];
          raw?: string;
          version?: number;
          version_label?: string;
          created_at?: string;
          updated_at?: string;
          icon_url?: string | null;
        };
        Relationships: [];
      };
      imported_mcp_versions: {
        Row: {
          id: string;
          mcp_id: string;
          version: number;
          description: string;
          manifest_url: string;
          homepage_url: string | null;
          transport: string;
          url: string | null;
          command: string | null;
          args: string[];
          env_keys: string[];
          headers: Json | null;
          tags: string[];
          raw: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          mcp_id: string;
          version: number;
          description?: string;
          manifest_url: string;
          homepage_url?: string | null;
          transport?: string;
          url?: string | null;
          command?: string | null;
          args?: string[];
          env_keys?: string[];
          headers?: Json | null;
          tags?: string[];
          raw?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          mcp_id?: string;
          version?: number;
          description?: string;
          manifest_url?: string;
          homepage_url?: string | null;
          transport?: string;
          url?: string | null;
          command?: string | null;
          args?: string[];
          env_keys?: string[];
          headers?: Json | null;
          tags?: string[];
          raw?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      daily_briefs: {
        Row: {
          id: string;
          category_slug: string;
          title: string;
          summary: string;
          what_changed: string;
          experiments: string[];
          items: Json;
          generated_at: string;
        };
        Insert: {
          id?: string;
          category_slug: string;
          title: string;
          summary?: string;
          what_changed?: string;
          experiments?: string[];
          items?: Json;
          generated_at?: string;
        };
        Update: {
          id?: string;
          category_slug?: string;
          title?: string;
          summary?: string;
          what_changed?: string;
          experiments?: string[];
          items?: Json;
          generated_at?: string;
        };
        Relationships: [];
      };
      loop_runs: {
        Row: {
          id: string;
          skill_slug: string;
          title: string;
          origin: string;
          trigger: string;
          status: string;
          started_at: string;
          finished_at: string;
          previous_version_label: string | null;
          next_version_label: string | null;
          href: string | null;
          summary: string | null;
          what_changed: string | null;
          body_changed: boolean | null;
          changed_sections: string[];
          editor_model: string | null;
          source_count: number;
          signal_count: number;
          messages: string[];
          sources: Json;
          diff_lines: Json;
          reasoning_steps: Json | null;
          error_message: string | null;
        };
        Insert: {
          id?: string;
          skill_slug: string;
          title: string;
          origin: string;
          trigger: string;
          status: string;
          started_at: string;
          finished_at: string;
          previous_version_label?: string | null;
          next_version_label?: string | null;
          href?: string | null;
          summary?: string | null;
          what_changed?: string | null;
          body_changed?: boolean | null;
          changed_sections?: string[];
          editor_model?: string | null;
          source_count?: number;
          signal_count?: number;
          messages?: string[];
          sources?: Json;
          diff_lines?: Json;
          reasoning_steps?: Json | null;
          error_message?: string | null;
        };
        Update: {
          id?: string;
          skill_slug?: string;
          title?: string;
          origin?: string;
          trigger?: string;
          status?: string;
          started_at?: string;
          finished_at?: string;
          previous_version_label?: string | null;
          next_version_label?: string | null;
          href?: string | null;
          summary?: string | null;
          what_changed?: string | null;
          body_changed?: boolean | null;
          changed_sections?: string[];
          editor_model?: string | null;
          source_count?: number;
          signal_count?: number;
          messages?: string[];
          sources?: Json;
          diff_lines?: Json;
          reasoning_steps?: Json | null;
          error_message?: string | null;
        };
        Relationships: [];
      };
      refresh_runs: {
        Row: {
          id: string;
          status: string;
          started_at: string;
          finished_at: string;
          generated_at: string | null;
          generated_from: string | null;
          write_local: boolean;
          upload_blob: boolean;
          refresh_category_signals: boolean;
          refresh_user_skills: boolean;
          refresh_imported_skills: boolean;
          focus_skill_slugs: string[];
          focus_imported_skill_slugs: string[];
          skill_count: number | null;
          category_count: number | null;
          daily_brief_count: number | null;
          error_message: string | null;
        };
        Insert: {
          id?: string;
          status: string;
          started_at: string;
          finished_at: string;
          generated_at?: string | null;
          generated_from?: string | null;
          write_local?: boolean;
          upload_blob?: boolean;
          refresh_category_signals?: boolean;
          refresh_user_skills?: boolean;
          refresh_imported_skills?: boolean;
          focus_skill_slugs?: string[];
          focus_imported_skill_slugs?: string[];
          skill_count?: number | null;
          category_count?: number | null;
          daily_brief_count?: number | null;
          error_message?: string | null;
        };
        Update: {
          id?: string;
          status?: string;
          started_at?: string;
          finished_at?: string;
          generated_at?: string | null;
          generated_from?: string | null;
          write_local?: boolean;
          upload_blob?: boolean;
          refresh_category_signals?: boolean;
          refresh_user_skills?: boolean;
          refresh_imported_skills?: boolean;
          focus_skill_slugs?: string[];
          focus_imported_skill_slugs?: string[];
          skill_count?: number | null;
          category_count?: number | null;
          daily_brief_count?: number | null;
          error_message?: string | null;
        };
        Relationships: [];
      };
      usage_events: {
        Row: {
          id: string;
          at: string;
          kind: string;
          source: string;
          label: string;
          path: string | null;
          route: string | null;
          method: string | null;
          status: number | null;
          duration_ms: number | null;
          ok: boolean | null;
          skill_slug: string | null;
          category_slug: string | null;
          details: string | null;
        };
        Insert: {
          id?: string;
          at?: string;
          kind: string;
          source: string;
          label: string;
          path?: string | null;
          route?: string | null;
          method?: string | null;
          status?: number | null;
          duration_ms?: number | null;
          ok?: boolean | null;
          skill_slug?: string | null;
          category_slug?: string | null;
          details?: string | null;
        };
        Update: {
          id?: string;
          at?: string;
          kind?: string;
          source?: string;
          label?: string;
          path?: string | null;
          route?: string | null;
          method?: string | null;
          status?: number | null;
          duration_ms?: number | null;
          ok?: boolean | null;
          skill_slug?: string | null;
          category_slug?: string | null;
          details?: string | null;
        };
        Relationships: [];
      };
      billing_events: {
        Row: {
          id: string;
          type: string;
          created_at: string;
          livemode: boolean;
          customer_id: string | null;
          customer_email: string | null;
          subscription_id: string | null;
          plan_slug: string | null;
          status: string | null;
          amount: number | null;
          currency: string | null;
        };
        Insert: {
          id?: string;
          type: string;
          created_at?: string;
          livemode?: boolean;
          customer_id?: string | null;
          customer_email?: string | null;
          subscription_id?: string | null;
          plan_slug?: string | null;
          status?: string | null;
          amount?: number | null;
          currency?: string | null;
        };
        Update: {
          id?: string;
          type?: string;
          created_at?: string;
          livemode?: boolean;
          customer_id?: string | null;
          customer_email?: string | null;
          subscription_id?: string | null;
          plan_slug?: string | null;
          status?: string | null;
          amount?: number | null;
          currency?: string | null;
        };
        Relationships: [];
      };
      purchases: {
        Row: {
          id: string;
          clerk_user_id: string;
          skill_slug: string;
          stripe_payment_intent_id: string;
          amount: number;
          currency: string;
          purchased_at: string;
        };
        Insert: {
          id: string;
          clerk_user_id: string;
          skill_slug: string;
          stripe_payment_intent_id: string;
          amount?: number;
          currency?: string;
          purchased_at?: string;
        };
        Update: {
          id?: string;
          clerk_user_id?: string;
          skill_slug?: string;
          stripe_payment_intent_id?: string;
          amount?: number;
          currency?: string;
          purchased_at?: string;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          customer_id: string;
          clerk_user_id: string | null;
          customer_email: string | null;
          plan_slug: string | null;
          status: string;
          cancel_at_period_end: boolean;
          current_period_end: string | null;
          checkout_completed_at: string | null;
          updated_at: string;
          latest_invoice_id: string | null;
        };
        Insert: {
          id: string;
          customer_id: string;
          clerk_user_id?: string | null;
          customer_email?: string | null;
          plan_slug?: string | null;
          status: string;
          cancel_at_period_end?: boolean;
          current_period_end?: string | null;
          checkout_completed_at?: string | null;
          updated_at?: string;
          latest_invoice_id?: string | null;
        };
        Update: {
          id?: string;
          customer_id?: string;
          clerk_user_id?: string | null;
          customer_email?: string | null;
          plan_slug?: string | null;
          status?: string;
          cancel_at_period_end?: boolean;
          current_period_end?: string | null;
          checkout_completed_at?: string | null;
          updated_at?: string;
          latest_invoice_id?: string | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
