import type {
  McpAuthType,
  McpInstallStrategy,
  McpVerificationStatus,
  SkillUpstreamRecord,
  TrustedSkillSourceRecord,
} from "@/lib/types";

type TrustedSkillSourceSeed = TrustedSkillSourceRecord;

type LocalUpstreamSeed = Omit<SkillUpstreamRecord, "body" | "logoUrl"> & {
  matchPathSuffix: string;
};

type McpNormalizationOverride = {
  docsUrl?: string;
  authType?: McpAuthType;
  installStrategy?: McpInstallStrategy;
  verificationStatus?: McpVerificationStatus;
  sandboxSupported?: boolean;
  sandboxNotes?: string;
};

export const TRUSTED_SKILL_SOURCE_SEEDS: TrustedSkillSourceSeed[] = [
  {
    id: "openai-skills",
    slug: "openai-skills",
    name: "OpenAI Skills",
    trustTier: "official",
    sourceType: "official-repo",
    homepageUrl: "https://github.com/openai/skills",
    repoUrl: "https://github.com/openai/skills",
    logoUrl: "https://github.com/openai.png?size=64",
    discoveryMode: "discover",
    searchQueries: ["openai skills github", "codex skills official"],
    tags: ["skills", "official", "codex"],
  },
  {
    id: "anthropic-skills",
    slug: "anthropic-skills",
    name: "Anthropic Skills",
    trustTier: "official",
    sourceType: "official-repo",
    homepageUrl: "https://github.com/anthropics/skills",
    repoUrl: "https://github.com/anthropics/skills",
    logoUrl: "https://cdn.simpleicons.org/anthropic",
    discoveryMode: "discover",
    searchQueries: ["anthropic skills github", "claude skills official"],
    tags: ["skills", "official", "claude"],
  },
  {
    id: "openai-docs",
    slug: "openai-docs",
    name: "OpenAI Docs",
    trustTier: "official",
    sourceType: "official-docs",
    homepageUrl: "https://platform.openai.com/docs",
    logoUrl: "https://github.com/openai.png?size=64",
    discoveryMode: "discover",
    searchQueries: ["openai responses api", "openai tool calling", "openai structured outputs"],
    tags: ["docs", "api", "openai"],
  },
  {
    id: "vercel-docs",
    slug: "vercel-docs",
    name: "Vercel Docs",
    trustTier: "official",
    sourceType: "vendor-docs",
    homepageUrl: "https://vercel.com/docs",
    logoUrl: "https://cdn.simpleicons.org/vercel",
    discoveryMode: "discover",
    searchQueries: ["vercel ai sdk", "vercel workflow", "vercel observability"],
    tags: ["docs", "vercel", "platform"],
  },
  {
    id: "nextjs-docs",
    slug: "nextjs-docs",
    name: "Next.js Docs",
    trustTier: "official",
    sourceType: "vendor-docs",
    homepageUrl: "https://nextjs.org/docs",
    logoUrl: "https://cdn.simpleicons.org/nextdotjs",
    discoveryMode: "discover",
    searchQueries: ["nextjs app router", "nextjs caching", "nextjs server actions"],
    tags: ["docs", "nextjs", "frontend"],
  },
  {
    id: "react-docs",
    slug: "react-docs",
    name: "React Docs",
    trustTier: "official",
    sourceType: "official-docs",
    homepageUrl: "https://react.dev",
    logoUrl: "https://cdn.simpleicons.org/react",
    discoveryMode: "discover",
    searchQueries: ["react compiler", "react hooks", "react server components"],
    tags: ["docs", "react", "frontend"],
  },
  {
    id: "modelcontextprotocol",
    slug: "modelcontextprotocol",
    name: "Model Context Protocol",
    trustTier: "standards",
    sourceType: "official-repo",
    homepageUrl: "https://github.com/modelcontextprotocol",
    repoUrl: "https://github.com/modelcontextprotocol",
    logoUrl: "https://github.com/modelcontextprotocol.png?size=64",
    discoveryMode: "discover",
    searchQueries: ["mcp specification", "mcp registry", "mcp server auth"],
    tags: ["mcp", "protocol", "registry"],
  },
  {
    id: "owasp",
    slug: "owasp",
    name: "OWASP",
    trustTier: "standards",
    sourceType: "official-docs",
    homepageUrl: "https://owasp.org",
    logoUrl: "https://owasp.org/assets/images/logo.svg",
    discoveryMode: "discover",
    searchQueries: ["owasp threat modeling", "owasp secure coding", "owasp api security"],
    tags: ["security", "standards", "appsec"],
  },
  {
    id: "supabase-docs",
    slug: "supabase-docs",
    name: "Supabase Docs",
    trustTier: "vendor",
    sourceType: "vendor-docs",
    homepageUrl: "https://supabase.com/docs",
    logoUrl: "https://cdn.simpleicons.org/supabase",
    discoveryMode: "discover",
    searchQueries: ["supabase rls", "supabase pgvector", "supabase edge functions"],
    tags: ["database", "supabase", "docs"],
  },
  {
    id: "cloudflare-docs",
    slug: "cloudflare-docs",
    name: "Cloudflare Docs",
    trustTier: "vendor",
    sourceType: "vendor-docs",
    homepageUrl: "https://developers.cloudflare.com",
    logoUrl: "https://cdn.simpleicons.org/cloudflare",
    discoveryMode: "discover",
    searchQueries: ["cloudflare workers", "durable objects", "cloudflare queues"],
    tags: ["cloudflare", "edge", "docs"],
  },
];

export const LOCAL_UPSTREAM_SKILLS: LocalUpstreamSeed[] = [
  {
    slug: "frontend-frontier",
    title: "Frontend Frontier",
    description: "High-signal UI art direction, motion, and distinct frontend execution.",
    category: "frontend",
    upstreamUrl: "https://github.com/openai/skills/tree/main/skills/frontend-frontier",
    upstreamKind: "skill",
    sourceId: "openai-skills",
    matchPathSuffix: "/skills/frontend-frontier/SKILL.md",
    tags: ["frontend", "art-direction", "motion"],
  },
  {
    slug: "motion-framer",
    title: "Motion",
    description: "Production React animation guidance for variants, gestures, layout, and presence.",
    category: "frontend",
    upstreamUrl: "https://github.com/openai/skills/tree/main/skills/motion-framer",
    upstreamKind: "skill",
    sourceId: "openai-skills",
    matchPathSuffix: "/skills/motion-framer/SKILL.md",
    tags: ["frontend", "animation", "react"],
  },
  {
    slug: "gsap-scrolltrigger",
    title: "GSAP + ScrollTrigger",
    description: "Scroll choreography, pinning, scrubbing, and multi-surface animation systems.",
    category: "frontend",
    upstreamUrl: "https://github.com/openai/skills/tree/main/skills/gsap-scrolltrigger",
    upstreamKind: "skill",
    sourceId: "openai-skills",
    matchPathSuffix: "/skills/gsap-scrolltrigger/SKILL.md",
    tags: ["frontend", "animation", "scroll"],
  },
  {
    slug: "react-three-fiber",
    title: "React Three Fiber",
    description: "Declarative 3D scenes in React using R3F and the Three.js ecosystem.",
    category: "frontend",
    upstreamUrl: "https://github.com/openai/skills/tree/main/skills/react-three-fiber",
    upstreamKind: "skill",
    sourceId: "openai-skills",
    matchPathSuffix: "/skills/react-three-fiber/SKILL.md",
    tags: ["frontend", "3d", "react"],
  },
  {
    slug: "security-best-practices",
    title: "Security Best Practices",
    description: "Language-aware secure coding review with actionable best-practice fixes.",
    category: "security",
    upstreamUrl: "https://github.com/openai/skills/tree/main/skills/security-best-practices",
    upstreamKind: "skill",
    sourceId: "openai-skills",
    matchPathSuffix: "/skills/security-best-practices/SKILL.md",
    tags: ["security", "secure-coding", "review"],
  },
  {
    slug: "security-threat-model",
    title: "Security Threat Model",
    description: "Repository-grounded threat modeling with abuse paths, trust boundaries, and mitigations.",
    category: "security",
    upstreamUrl: "https://github.com/openai/skills/tree/main/skills/security-threat-model",
    upstreamKind: "skill",
    sourceId: "openai-skills",
    matchPathSuffix: "/skills/security-threat-model/SKILL.md",
    tags: ["security", "threat-modeling", "architecture"],
  },
  {
    slug: "openai-docs",
    title: "OpenAI Docs",
    description: "Official OpenAI docs workflow for model selection, API changes, and canonical guidance.",
    category: "a2a",
    upstreamUrl: "https://platform.openai.com/docs",
    upstreamKind: "docs-pack",
    sourceId: "openai-docs",
    matchPathSuffix: "/skills/.system/openai-docs/SKILL.md",
    tags: ["openai", "docs", "api"],
  },
  {
    slug: "vercel-ai-sdk",
    title: "Vercel AI SDK",
    description: "Official AI SDK skill for chat, structured output, tool calling, agents, and streaming.",
    category: "a2a",
    upstreamUrl: "https://vercel.com/docs/ai",
    upstreamKind: "plugin-skill",
    sourceId: "vercel-docs",
    matchPathSuffix: "/skills/ai-sdk/SKILL.md",
    tags: ["vercel", "ai-sdk", "agents"],
  },
  {
    slug: "vercel-ai-gateway",
    title: "Vercel AI Gateway",
    description: "Routing, failover, and multi-provider model access through a unified gateway.",
    category: "a2a",
    upstreamUrl: "https://vercel.com/docs/ai-gateway",
    upstreamKind: "plugin-skill",
    sourceId: "vercel-docs",
    matchPathSuffix: "/skills/ai-gateway/SKILL.md",
    tags: ["vercel", "gateway", "providers"],
  },
  {
    slug: "vercel-nextjs",
    title: "Next.js",
    description: "Official Next.js App Router patterns spanning routing, rendering, caching, and server actions.",
    category: "frontend",
    upstreamUrl: "https://nextjs.org/docs",
    upstreamKind: "plugin-skill",
    sourceId: "nextjs-docs",
    matchPathSuffix: "/skills/nextjs/SKILL.md",
    tags: ["nextjs", "app-router", "frontend"],
  },
  {
    slug: "vercel-observability",
    title: "Vercel Observability",
    description: "Logs, traces, analytics, and performance instrumentation for production systems.",
    category: "infra",
    upstreamUrl: "https://vercel.com/docs/observability",
    upstreamKind: "plugin-skill",
    sourceId: "vercel-docs",
    matchPathSuffix: "/skills/observability/SKILL.md",
    tags: ["observability", "logging", "tracing"],
  },
  {
    slug: "vercel-workflow",
    title: "Vercel Workflow",
    description: "Durable workflow orchestration for long-running tasks, retries, and step execution.",
    category: "a2a",
    upstreamUrl: "https://vercel.com/docs/workflow",
    upstreamKind: "plugin-skill",
    sourceId: "vercel-docs",
    matchPathSuffix: "/skills/workflow/SKILL.md",
    tags: ["workflow", "agents", "durable-execution"],
  },
  {
    slug: "vercel-api",
    title: "Vercel API",
    description: "Live platform access for deployments, env vars, docs, and operational tooling.",
    category: "ops",
    upstreamUrl: "https://vercel.com/docs/mcp",
    upstreamKind: "plugin-skill",
    sourceId: "vercel-docs",
    matchPathSuffix: "/skills/vercel-api/SKILL.md",
    tags: ["vercel", "mcp", "operations"],
  },
  {
    slug: "gh-fix-ci",
    title: "GitHub CI Fix",
    description: "Diagnose failing GitHub PR checks and repair CI with logs-first workflow.",
    category: "ops",
    upstreamUrl: "https://github.com/openai/skills/tree/main/skills/gh-fix-ci",
    upstreamKind: "skill",
    sourceId: "openai-skills",
    matchPathSuffix: "/skills/gh-fix-ci/SKILL.md",
    tags: ["github", "ci", "ops"],
  },
];

export const SKILL_UPSTREAM_LINKS: Record<string, string[]> = {
  "frontend-frontier": ["frontend-frontier"],
  "motion-framer": ["motion-framer"],
  "gsap-scrolltrigger": ["gsap-scrolltrigger"],
  "react-three-fiber": ["react-three-fiber"],
  "nextjs-patterns": ["vercel-nextjs", "frontend-frontier"],
  "observability-stack": ["vercel-observability"],
  "agent-orchestration": ["vercel-workflow", "vercel-ai-sdk", "openai-docs"],
  "mcp-development": ["vercel-api", "openai-docs"],
  "prompt-engineering": ["openai-docs"],
  "tool-use-patterns": ["openai-docs", "vercel-ai-sdk"],
  "rag-pipelines": ["openai-docs", "vercel-ai-sdk"],
  "security-best-practices": ["security-best-practices"],
  "security-threat-model": ["security-threat-model"],
  "gh-actions-ci": ["gh-fix-ci"],
  "serverless-architecture": ["vercel-workflow", "vercel-api"],
};

export const DIRECT_TRANSPLANT_SKILLS: Record<string, string> = {
  "frontend-frontier": "frontend-frontier",
  "motion-framer": "motion-framer",
  "gsap-scrolltrigger": "gsap-scrolltrigger",
  "react-three-fiber": "react-three-fiber",
  "nextjs-patterns": "vercel-nextjs",
  "observability-stack": "vercel-observability",
  "security-best-practices": "security-best-practices",
  "security-threat-model": "security-threat-model",
};

export const FEATURED_SKILL_ORDER = [
  "frontend-frontier",
  "nextjs-patterns",
  "agent-orchestration",
  "motion-framer",
  "database-patterns",
  "tool-use-patterns",
  "mcp-development",
  "security-best-practices",
  "web-performance",
  "observability-stack",
  "seo-geo",
  "rag-pipelines",
];

export const FEATURED_REASON_OVERRIDES: Partial<Record<string, string>> = {
  "frontend-frontier": "Broadest appeal, strong upstream corpus, and directly useful for anyone shipping UI in anger.",
  "nextjs-patterns": "High demand surface area, official upstream docs, and immediate leverage for the app-router-heavy crowd.",
  "agent-orchestration": "Crosses tooling, architecture, and automation. This is the category people keep tripping over in production.",
  "mcp-development": "Directly tied to MCP adoption and a current source of real product pain, so surfacing it is not optional.",
  "security-best-practices": "High-trust, high-stakes guidance with immediate value across almost every repo.",
};

export const QUALITY_SCORE_OVERRIDES: Partial<Record<string, number>> = {
  "frontend-frontier": 98,
  "nextjs-patterns": 96,
  "agent-orchestration": 95,
  "tool-use-patterns": 95,
  "security-best-practices": 94,
  "mcp-development": 94,
  "observability-stack": 92,
};

export const MCP_NORMALIZATION_OVERRIDES: Record<string, McpNormalizationOverride> = {
  Filesystem: {
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    authType: "none",
    installStrategy: "npx",
    verificationStatus: "verified",
    sandboxSupported: true,
    sandboxNotes: "Runs locally via npx inside the Loop runtime and needs no external credentials.",
  },
  Memory: {
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
    authType: "none",
    installStrategy: "npx",
    verificationStatus: "verified",
    sandboxSupported: true,
    sandboxNotes: "Safe default MCP for persistent scratch memory across runs.",
  },
  "Sequential Thinking": {
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    authType: "none",
    installStrategy: "npx",
    verificationStatus: "verified",
    sandboxSupported: true,
    sandboxNotes: "Useful when the agent needs explicit decomposition instead of silent chain-of-thought mush.",
  },
  Fetch: {
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
    authType: "none",
    installStrategy: "npx",
    verificationStatus: "verified",
    sandboxSupported: true,
    sandboxNotes: "Reliable default web fetcher for public URLs and markdown conversion.",
  },
  Git: {
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/git",
    authType: "none",
    installStrategy: "npx",
    verificationStatus: "verified",
    sandboxSupported: true,
    sandboxNotes: "Works against local repositories without external auth when the repo is mounted.",
  },
  GitHub: {
    docsUrl: "https://github.com/github/github-mcp-server",
    authType: "pat",
    installStrategy: "npx",
    verificationStatus: "verified",
    sandboxSupported: true,
    sandboxNotes: "Requires GITHUB_PERSONAL_ACCESS_TOKEN with the right scopes, then behaves consistently in the sandbox.",
  },
  Vercel: {
    docsUrl: "https://vercel.com/docs/mcp",
    authType: "session",
    installStrategy: "remote-http",
    verificationStatus: "verified",
    sandboxSupported: true,
    sandboxNotes: "Remote MCP endpoint. Works when the app server has valid Vercel auth context.",
  },
  Linear: {
    docsUrl: "https://linear.app/docs",
    authType: "api-key",
    installStrategy: "remote-http",
    verificationStatus: "verified",
    sandboxSupported: true,
    sandboxNotes: "High-value sandbox MCP when LINEAR_API_KEY is configured.",
  },
  Notion: {
    authType: "api-key",
    verificationStatus: "partial",
    sandboxSupported: true,
    sandboxNotes: "Usable once NOTION_API_KEY is present. Keep it visible but clearly credential-gated.",
  },
  Slack: {
    authType: "api-key",
    verificationStatus: "partial",
    sandboxSupported: true,
    sandboxNotes: "Credential-gated. Hide from default demos unless Slack auth is configured.",
  },
  Figma: {
    docsUrl: "https://www.figma.com/developers/mcp",
    authType: "session",
    verificationStatus: "verified",
    sandboxSupported: true,
    sandboxNotes: "Useful for design-to-code flows when the connected Figma session is present on the app server.",
  },
  Playwright: {
    docsUrl: "https://playwright.dev/docs",
    authType: "none",
    verificationStatus: "verified",
    sandboxSupported: true,
    sandboxNotes: "Excellent default browser MCP for sandbox runs and visual verification.",
  },
  Exa: {
    authType: "api-key",
    verificationStatus: "partial",
    sandboxSupported: true,
    sandboxNotes: "Great research MCP, but only after EXA_API_KEY is wired.",
  },
  Firecrawl: {
    authType: "api-key",
    verificationStatus: "partial",
    sandboxSupported: true,
    sandboxNotes: "Useful for structured site extraction when FIRECRAWL_API_KEY is configured.",
  },
  "Brave Search": {
    authType: "api-key",
    verificationStatus: "partial",
    sandboxSupported: true,
    sandboxNotes: "Search MCP with straightforward API-key auth.",
  },
  Supabase: {
    authType: "api-key",
    verificationStatus: "partial",
    sandboxSupported: true,
    sandboxNotes: "Powerful, but only once project URL and service credentials are configured correctly.",
  },
  Sentry: {
    authType: "api-key",
    verificationStatus: "partial",
    sandboxSupported: true,
    sandboxNotes: "Useful for production debugging when SENTRY_AUTH_TOKEN is available.",
  },
};
