export const FREE_AUTOMATION_LIMIT = 3;
export const OPERATOR_AUTOMATION_LIMIT = Infinity;
export const MAX_SKILLS_PER_USER = 10;
export const MAX_PUBLIC_SKILLS_PER_USER = 20;
export const SKILL_CREATE_COOLDOWN_MS = 30 * 1000;
export const MAX_SLUG_COLLISION_ATTEMPTS = 10;

export const FREE_MANUAL_UPDATE_COOLDOWN_MS = 15 * 60 * 1000;
export const OPERATOR_MANUAL_UPDATE_COOLDOWN_MS = 5 * 60 * 1000;
/** @deprecated Use FREE_MANUAL_UPDATE_COOLDOWN_MS / OPERATOR_MANUAL_UPDATE_COOLDOWN_MS */
export const MANUAL_UPDATE_COOLDOWN_MS = FREE_MANUAL_UPDATE_COOLDOWN_MS;

export const AUTOMATION_PROXIMITY_MS = 60 * 60 * 1000;

export const FREE_SANDBOX_CONVERSATION_LIMIT = 5;
export const OPERATOR_SANDBOX_CONVERSATION_LIMIT = Infinity;

export const FREE_CONVERSATION_LIMIT = 10;
export const OPERATOR_CONVERSATION_LIMIT = Infinity;

export const FREE_DAILY_AGENT_RUN_LIMIT = 20;
export const OPERATOR_DAILY_AGENT_RUN_LIMIT = Infinity;

export const MS_PER_DAY = 24 * 60 * 60 * 1000;
